export const users = Array(8).fill({
    name: "John the ripper",
    ref: "1512458624-AA54",
    parentName: "First name last name",
    contact: "0649522179358",
    avatar: "https://api.dicebear.com/9.x/adventurer-neutral/svg", 
  });
 export const classes = [
    {
      name: "1ere Scientifique - S1",
      teacher: "mohammed mohammed",
      students: 17,
      average: "14.20",
      averageType: "success",
      count: 14,
    },
    {
      name: "1ere Literaire - S1",
      teacher: "Mme. Kadouri amel",
      students: 12,
      average: "9.24",
      averageType: "danger",
      count: 9,
    },
    {
      name: "2eme Science Experimentales - S1",
      teacher: "Mr. Salah Ahmed",
      students: 9,
      average: "vide",
      averageType: "neutral",
      count: 9,
    },
    {
      name: "2eme Matheleme - Math1",
      teacher: "Mr. Riemann Pascal",
      students: 17,
      average: "vide",
      averageType: "neutral",
      count: 14,
    },
    {
      name: "2ere Literaire - Ltr1",
      teacher: "Mme. Kadouri amel",
      students: 12,
      average: "vide",
      averageType: "neutral",
      count: 9,
    },
    {
      name: "3eme Science Experimentales - S1",
      teacher: "Mr. Salah Ahmed",
      students: 9,
      average: "vide",
      averageType: "neutral",
      count: 9,
    },{
      name: "1ere Scientifique - S1",
      teacher: "mohammed mohammed",
      students: 17,
      average: "14.20",
      averageType: "success",
      count: 14,
    },{
      name: "1ere Scientifique - S1",
      teacher: "mohammed mohammed",
      students: 17,
      average: "14.20",
      averageType: "success",
      count: 14,
    }
  ];